temoto:
  human_input: "current_cmd_frame"
  base_frame: "base_link"
  num_ee: 1 # How many end-effectors might the user want to control?
  ee: # Specify all move_group/ee pairs
    ee0: # use this naming convention (ee + #). If one is used more heavily, put it first.
      end_effector: "temoto_end_effector"
      movegroup: "manipulator"
      manip_stl: "package://temoto/meshes/MotorMount_Output.stl"
      jog_topic: "/jog_arm_server/delta_jog_cmds"
      wrist_joint_name: herbie/joint_5
      allow_compliant_jog: false
      joint_jog_topic: "/NOT_IMPLEMENTED"

  temoto_spacenav_pose_cmd_topic: "/spacenav/joy"
  temoto_xbox_pose_cmd_topic: ""
  temoto_leap_pose_cmd_topic: ""

   # navigate or manipulate
  enable_navigation: false
  enable_manipulation: true

  input_voice_topic: "stt/spoken_text"

  motion_scales:
    pt_to_pt:
      nav_pos_scale: 0.048
      nav_rot_scale: 0.08
      manip_pos_scale: 0.005
      manip_rot_scale: 0.012
    jog:
      nav_pos_scale: 0.3
      nav_rot_scale: 0.2
      manip_pos_scale: 1.
      manip_rot_scale: 1.
