temoto:
  human_input: "temoto_command_frame"
  base_frame: "base_link"
  num_ee: 1 # How many end-effectors might the user want to control?
  ee: # Specify all move_group/ee pairs
    ee0: # use this naming convention (ee + #). If one is used more heavily, put it first.
      end_effector: "end_effector"
      movegroup: "manipulator"
      manip_stl: "package://temoto_support/meshes/2_finger_140_gripper_marker.stl"
      jog_topic: ""
      joint_jog_topic: ""
      wrist_joint_name: "wrist_3_joint"
      allow_compliant_jog: false
      force_torque_frame: ""
      force_torque_topic: ""

  temoto_spacenav_pose_cmd_topic: ""
  temoto_xbox_pose_cmd_topic: ""
  temoto_leap_pose_cmd_topic: "leap_motion_output"

  enable_navigation: false
  enable_manipulation: true

  input_voice_topic: "stt/spoken_text"

  motion_scales:
    pt_to_pt:
      nav_pos_scale: 0.01
      nav_rot_scale: 0.008
      manip_pos_scale: 0.006
      manip_rot_scale: 0.008
    jog:
      nav_pos_scale: 0.3
      nav_rot_scale: 0.2
      manip_pos_scale: 1.
      manip_rot_scale: 1.
