temoto_frames:
  human_input: "current_cmd_frame"
  end_effector: "temoto_end_effector"
  mobile_base: "base_link"
temoto:
  # LeapMotion or SpaceNav
  leap_input: false
  spacenav_input: true
  primary_hand: "left"
  temoto_pose_cmd_topic: "spacenav/joy" #"leap_motion_output"

   # navigate or manipulate
  navigate: false
  manipulate: true

  manip_stl: "package://temoto_support/meshes/2_finger_140_gripper_marker.stl" #"package://temoto_support/meshes/manip_cube.stl"
  input_voice_topic: "stt/spoken_text"
  movegroup: "manipulator"
