temoto_frames:
  human_input: "current_cmd_frame"
  end_effector: "temoto_end_effector"
  mobile_base: "base_link"
temoto:
  # LeapMotion or SpaceNav
  leap_input: true
  spacenav_input: false
  primary_hand: "left"
  temoto_pose_cmd_topic: "leap_motion_output" #"/temoto/spacenav/joy"

   # navigate or manipulate
  navigate: false
  manipulate: true

  manip_stl: "package://temoto_support/meshes/manip_cube.stl" #"package://temoto_support/meshes/2_finger_140_gripper_marker.stl"
  input_voice_topic: "stt/spoken_text"
  movegroup: "manipulator"
