temoto:
  human_input: "current_cmd_frame"
  base_frame: "base_link"
  num_ee: 2 # How many end-effectors might the user want to control?
  ee: # Specify all move_group/ee pairs
    ee0: # use this naming convention (ee + #). If one is used more heavily, put it first.
      end_effector: "r_temoto_end_effector"
      movegroup: "right_ur5_temoto"
      manip_stl: "package://temoto/meshes/robotiq_2f_140_visual_temoto.stl"
      jog_topic: "right_arm/jog_arm_server/delta_jog_cmds"
      joint_jog_topic: "right_arm/jog_arm_server/joint_delta_jog_cmds"
      wrist_joint_name: "right_ur5_wrist_3_joint"
      force_torque_frame: "right_ur5_base"
      force_torque_topic: "right_ur5_wrench"
      gripper_type: "robotiq" # robotiq, hebi, or nothing
      gripper_topic: "/Robotiq2FGripperRobotOutput" # empty if no gripper or no topic required
      toggle_compliance_service: "/right_ur5compliance_controller/toggle_compliance"
      bias_compliance_service: "/right_wrench_to_joint_vel_pub/bias_compliance_calcs"
      compliance_dimensions_service: "/right_wrench_to_joint_vel_pub/disable_compliance_dimensions"
      home_pose_name: "right_ur5_temoto"
    ee1:
      end_effector: "left_ur5_ee_link"
      movegroup: "left_ur5"
      manip_stl: "package://temoto/meshes/manip_cube.stl"
      jog_topic: "left_arm/jog_arm_server/delta_jog_cmds"
      joint_jog_topic: "left_arm/jog_arm_server/joint_delta_jog_cmds"
      wrist_joint_name: "left_ur5_wrist_3_joint"
      force_torque_frame: "left_ur5_base"
      force_torque_topic: "left_ur5_wrench"
      gripper_type: "" # robotiq, hebi, or nothing
      gripper_topic: "" # empty if no gripper or no topic required
      toggle_compliance_service: "/left_ur5compliance_controller/toggle_compliance"
      bias_compliance_service: "/left_wrench_to_joint_vel_pub/bias_compliance_calcs"
      compliance_dimensions_service: "/left_wrench_to_joint_vel_pub/disable_compliance_dimensions"
      home_pose_name: "left_ur5_temoto"

  temoto_spacenav_pose_cmd_topic: "/spacenav/joy"
  temoto_xbox_pose_cmd_topic: ""
  temoto_leap_pose_cmd_topic: ""

  enable_navigation: true
  enable_manipulation: true

  input_voice_topic: "stt/spoken_text"

  motion_scales:
    pt_to_pt:
      nav_pos_scale: 0.01
      nav_rot_scale: 0.008
      manip_pos_scale: 0.006
      manip_rot_scale: 0.008
    jog:
      nav_pos_scale: 0.3
      nav_rot_scale: 0.2
      manip_pos_scale: 1.
      manip_rot_scale: 1.

  image_topics:
    - "/camera_right/color/image_raw"
    - "/camera_left/color/image_raw"
    - "/camera_hmd/image_raw"
    - "transparent"
