temoto_frames:
  human_input: "current_cmd_frame"
  base_frame: "base_link"
  num_ee: 2 # How many end-effectors might the user want to control?
  ee: # Specify all move_group/ee pairs
    ee0: # use this naming convention (ee + #). If one is used more heavily, put it first.
      end_effector: "r_temoto_end_effector"
      movegroup: "right_ur5_temoto"
      manip_stl: "package://temoto_support/meshes/2_finger_140_gripper_marker.stl"
    ee1:
      end_effector: "left_ur5_ee_link"
      movegroup: "left_ur5"
      manip_stl: "package://temoto_support/meshes/manip_cube.stl"

temoto:
  temoto_spacenav_pose_cmd_topic: "/spacenav/joy"
  temoto_xbox_pose_cmd_topic: "/joy"
  incoming_jog_topic: "right_arm/jog_arm_server/delta_jog_cmds"

  # navigate or manipulate
  navigate: false
  manipulate: true

  input_voice_topic: "stt/spoken_text"

  motion_scales:
    pt_to_pt:
      nav_pos_scale: 0.01
      nav_rot_scale: 0.01
      manip_pos_scale: 0.008
      manip_rot_scale: 0.01
    jog:
      nav_pos_scale: 0.3
      nav_rot_scale: 0.2
      manip_pos_scale: 1.
      manip_rot_scale: 1.
